### PR TITLE
Check if verbose mode True or not

### PR DESCRIPTION
**Pull request by toufik-airane**
Because without this check, I'm always in verbose mode.

### CODE REVIEW

**Comment by PaulSec** [comment]
Hey there :) 

No need, to add `== True`, it's already what's happening. Cheers!

**Comment by toufik-airane** [comment]
Yes, I know. So why I'm always in verbose mode without this check ... (è_é)

**Comment by PaulSec** [comment]
Oh sorry for that. 
We changed the constructor for the class and now, instead of passing a dictionary such as `{verbose: True}`, we just pass the flag `True` or `False`. 

Check the updated example. 

Cheers!

**Comment by toufik-airane** [comment]
Oh ok :) that why, thx !

**Pull request closed without merging**
