### PR TITLE
print_function, make it happy with Py2

### PR DESCRIPTION
**Pull request by paralax**

### CODE REVIEW

**Comment by PaulSec** [comment]
Reviewed and merged! Thanks Jose :+1:

**Comment by aancw** [comment]
@PaulSec If you don't mind, please update pypi package(https://pypi.python.org/pypi/dnsdumpster) for this fix because i'm still using python2 :)

I want to include your API as part of my plugins ( https://github.com/aancw/Belati )

Thanks!

**Comment by PaulSec** [comment]
Sure, I will do this at home tonight!

**Comment by aancw** [comment]
Thanks!

And one more little change for this repo:

```
Then import the class and start playing:

from dnsdumpster.DNSDumpsterAPI import DNSDumpsterAPI
results = DNSDumpsterAPI.DNSDumpsterAPI().search('microsoft.com')
```

You are mistyping, it should be:

```
Then import the class and start playing:

from dnsdumpster.DNSDumpsterAPI import DNSDumpsterAPI
results = DNSDumpsterAPI().search('microsoft.com')
```

**Comment by PaulSec** [comment]
Done for both! 
Thank you 👍

**Pull request merged**
